# run jekyll with docker container
#
# install docker && docker-compose
# https://docs.docker.com/compose/install/
# then run docker-compose up

jekyll:
    image: jekyll/jekyll:pages
    command: jekyll serve --watch --incremental
    ports:
        - 4000:4000
    volumes:
        - .:/srv/jekyll
